version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: springboot_mysql_example
      MYSQL_USER: jumana
      MYSQL_PASSWORD: Jujujumana
    ports:
      - "3000:3306"
    volumes:
      - my-db:/var/lib/mysql
  web-app:
    depends_on:
        - db
    restart: on-failure
    links: 
        - "db:db"
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
volumes:  
  my-db:  