name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # Change this to your desired Java version

    - name: Build JAR
      run: |
        mvn package  # Use this command if you're using Maven
        # or
        # ./gradlew build  # Use this command if you're using Gradle

    - name: Build Docker image
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0
      run: |
        docker build . -t spring-boot-1




